# ============================================================ #

[dataset]
dataset_name = "QM9"
version_select = "latest"
num_workers = 4
pin_memory = true
properties_of_interest = ["atomic_numbers", "geometry", "internal_energy_at_0K", "dipole_moment"]
element_filter = []

[dataset.properties_assignment]
atomic_numbers = "atomic_numbers"
positions = "geometry"
E = "internal_energy_at_0K"

# ============================================================ #

[potential]
potential_name = "SchNet"

[potential.core_parameter]
number_of_radial_basis_functions = 64
maximum_interaction_radius = "5.0 angstrom"
number_of_interaction_modules = 3
number_of_filters = 64
shared_interactions = true
predicted_properties = ["per_atom_energy", "per_atom_charge"]
predicted_dim = [1, 1]

[potential.core_parameter.activation_function_parameter]
activation_function_name = "ShiftedSoftplus"
[potential.core_parameter.featurization]
properties_to_featurize = ['atomic_number', "per_system_total_charge"]

[potential.core_parameter.featurization.atomic_number]
maximum_atomic_number = 101
number_of_per_atom_features = 32

[potential.postprocessing_parameter]
properties_to_process = ['per_atom_energy', 'per_atom_charge']

[potential.postprocessing_parameter.per_atom_energy]
normalize = false
from_atom_to_system_reduction = true
keep_per_atom_property = true

[potential.postprocessing_parameter.per_atom_charge]
conserve = true
conserve_strategy= "default"

[potential.postprocessing_parameter.general_postprocessing_operation]
calculate_molecular_self_energy = true

# ============================================================ #

[runtime]
save_dir = "lightning_logs"
experiment_name = "{potential_name}_{dataset_name}"
local_cache_dir = "./cache"
accelerator = "gpu"
number_of_nodes = 1
devices = [0]                                        #[0,1,2,3]
checkpoint_path = "None"
simulation_environment = "PyTorch"
log_every_n_steps = 50
verbose = false

# ============================================================ #

[training]
number_of_epochs = 500
remove_self_energies = true
batch_size = 128
lr = 5e-4
monitor = "val/per_system_energy/rmse"
shift_center_of_mass_to_origin = false
log_norm = false
plot_frequency = 1
# ------------------------------------------------------------ #
[training.experiment_logger]
logger_name = "wandb"
[training.experiment_logger.wandb_configuration]
save_dir = "logs"
project = "training"
group = "exp01"
log_model = true
job_type = "testing"
tags = ["v_0.1.0"]
notes = "testing"
# ------------------------------------------------------------ #
[training.lr_scheduler]
scheduler_name = "ReduceLROnPlateau"
frequency = 1
mode = "min"
monitor = "val/per_system_energy/rmse"
factor = 0.5
patience = 10
cooldown = 15
min_lr = 1e-6
threshold = 0.1
threshold_mode = "abs"
interval = "epoch"
# ------------------------------------------------------------ #
[training.loss_parameter]
loss_components = ['per_atom_energy']
[training.loss_parameter.weight]
per_atom_energy = 1.0
# ------------------------------------------------------------ #
[training.early_stopping]
verbose = true
min_delta = 0.1
patience = 100
# ------------------------------------------------------------ #
[training.splitting_strategy]
name = "random_record_splitting_strategy"
data_split = [0.8, 0.1, 0.1]
seed = 41
# ------------------------------------------------------------ #

# ============================================================ #
